import Foundation

struct CMemoryGenerationResult {
    let output: String
    let functionNames: [String]
}

private struct ClangASTNode: Decodable {
    struct TypeInfo: Decodable {
        let qualType: String?
        let desugaredQualType: String?
    }

    let kind: String
    let name: String?
    let isImplicit: Bool?
    let type: TypeInfo?
    let inner: [ClangASTNode]?
}

/// Clang's implicit libc builtins are callable from Swift but omitted from
/// Darwin's symbol graph. Sweep the SDK header AST and select the read-only
/// relative-pointer family by declaration properties: builtin function,
/// pointer result, and `(const void *, int, size_t)` parameters. The emitted
/// call uses the metadata-provided spelling, so runtime code contains no C API
/// name allowlist.
func generateCMemoryBridge(sdkPath: String) throws -> CMemoryGenerationResult {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/xcrun")
    process.arguments = [
        "clang", "-isysroot", sdkPath,
        "-x", "c", "-std=c17",
        "-Xclang", "-ast-dump=json",
        "-fsyntax-only", "-include", "string.h", "/dev/null",
    ]
    let output = Pipe()
    let errors = Pipe()
    process.standardOutput = output
    process.standardError = errors
    try process.run()
    // AST JSON is larger than a pipe's kernel buffer. Drain it while clang
    // runs; waiting first would deadlock once that buffer fills.
    let data = output.fileHandleForReading.readDataToEndOfFile()
    process.waitUntilExit()
    let errorText = String(
        data: errors.fileHandleForReading.readDataToEndOfFile(),
        encoding: .utf8) ?? ""
    guard process.terminationStatus == 0 else {
        throw NSError(
            domain: "BridgeGen.CMemory", code: Int(process.terminationStatus),
            userInfo: [NSLocalizedDescriptionKey:
                "clang string.h AST sweep failed:\n\(errorText)"])
    }

    let root = try JSONDecoder().decode(ClangASTNode.self, from: data)
    var selected = Set<String>()
    func visit(_ node: ClangASTNode) {
        defer { node.inner?.forEach(visit) }
        guard node.kind == "FunctionDecl",
              node.isImplicit != true,
              let name = node.name,
              name.first?.isLetter == true,
              let functionType = node.type?.qualType,
              functionType.hasPrefix("void *("),
              node.inner?.contains(where: { $0.kind == "BuiltinAttr" }) == true
        else { return }
        let parameters = (node.inner ?? []).filter { $0.kind == "ParmVarDecl" }
        guard parameters.count == 3 else { return }
        func canonicalType(_ parameter: ClangASTNode) -> String {
            parameter.type?.desugaredQualType
                ?? parameter.type?.qualType ?? ""
        }
        guard canonicalType(parameters[0]) == "const void *",
              canonicalType(parameters[1]) == "int",
              canonicalType(parameters[2]) == "unsigned long"
        else { return }
        selected.insert(name)
    }
    visit(root)
    let names = selected.sorted()

    var source = """
    // GENERATED by BridgeGen from the Darwin SDK's Clang string.h AST.
    // Do not edit. Regenerate: swift run BridgeGen --emit
    import Darwin
    import SwiftInterpreter

    enum GeneratedCMemoryBridge {
        static func function(named name: String) -> HostFunction? {
            switch name {

    """
    for name in names {
        source += """
            case \(String(reflecting: name)):
                return HostFunction(name: name) { args, _ in
                    try generatedCRelativePointerFunction(
                        memory: args.positional(0),
                        scalar: args.positional(1),
                        count: args.positional(2)
                    ) { pointer, scalar, count in
                        Darwin.`\(name)`(pointer, scalar, count)
                    }
                }

        """
    }
    source += """
            default:
                return nil
            }
        }
    }
    """
    return CMemoryGenerationResult(
        output: source + "\n", functionNames: names)
}
